CREATE TABLE IF NOT EXISTS `generations` (
  `id` varchar(100) NOT NULL,
  `userId` int NOT NULL,
  `type` enum('image','video') NOT NULL,
  `prompt` longtext NOT NULL,
  `style` varchar(50) NOT NULL,
  `provider` varchar(50) NOT NULL,
  `quality` varchar(20),
  `duration` int,
  `width` int DEFAULT 1024,
  `height` int DEFAULT 768,
  `url` text,
  `thumbnailUrl` text,
  `status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
  `error` text,
  `processingTime` int,
  `fromCache` tinyint(1) NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expiresAt` timestamp NULL,
  PRIMARY KEY (`id`),
  KEY `userId_idx` (`userId`),
  KEY `status_idx` (`status`),
  KEY `createdAt_idx` (`createdAt`)
);
